[package]
name = "miso_record_seal_policy"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_record = { git = "https://github.com/misofm/record.git", rev = "c3f5310e0f52b1aa5553636c7f8edae7d01d0010" }
miso = { git = "https://github.com/misonetwork/protocol.git", rev = "7bda0bb740c32a75ef76c0739cb671b3de77d338" }
