[package]
name = "miso_record_seal_policy"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_record = { git = "https://github.com/misofm/record.git", rev = "a235ffd41e8d2b1e76e1c7bba292e5ee11074e5b" }
