[package]
name = "miso_record_seal_policy"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_pressing = { git = "https://github.com/misofm/pressing.git", rev = "dc44fa7c61ecdd92e4c672057b4c6142e874053e" }
miso_record = { git = "https://github.com/misofm/record.git", subdir = "move", rev = "46dadad176ceadef8f698498968a1688af96960b" }
